spring.application.name=AnalysisServiceMS
server.port=8081

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/analysisdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

python.genai.url=http://localhost:5001/api/analyze

spring.cloud.consul.enabled=false
spring.cloud.service-registry.auto-registration.enabled=false