spring.application.name=LogIngestionServiceMS
server.port=8084

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/logdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG


spring.cloud.consul.enabled=false
spring.cloud.service-registry.auto-registration.enabled=false